spring.application.name=demo

spring.datasource.url=jdbc:mysql://mysql-198ca1b2-anurag-7cec.l.aivencloud.com:16674/defaultdb?sslMode=REQUIRED&useSSL=true

spring.datasource.username=avnadmin
spring.datasource.password=AVNS_1PcIi1qfIXREgJJK3UC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}
